### ISSUE TITLE
How to modify config?

### ISSUE THREAD

**Issue by xuewuji** [Egoistically/Perseus#1]
I'm a newcomer,Can you tell me where is /sdcard/Perseus?

**Comment by Egoistically** [comment]
When the library is loaded, that directory will be created (alongside the config file) if it doesn't already exist.

**Comment by xuewuji** [comment]
Can you teach me how to load so library?I tried load libPerseus.so on com.unity3d.play.UnityPlayer,but I failed.

**Comment by Egoistically** [comment]
I personally went for `com.unity3d.player.UnityPlayerActivity`, hope that works for you as well. If not, feel free to add me on discord (shirome#0001).

**Comment by Egoistically** [comment]
Solved on Discord.
