### ISSUE TITLE
Detail documentation about feature

### ISSUE THREAD

**Issue by ZixMatrix** [Egoistically/Perseus#2]
sorry i want to ask you something about the features

would you mind to add more detail to the feature or about what will happened if we set true or false to the perseus.ini, please ?

thank you very much

**Comment by n0k0m3** [comment]
The key name is already clear enough about the functionalities of it.

> what will happened if we set true or false to the perseus.ini
You need to test it yourself

**Comment by ZixMatrix** [comment]
thanks already done that before
any other way to set our ship evasion ?
