### ISSUE TITLE
Where is the source code

### ISSUE THREAD

**Issue by zunda-arrow** [Egoistically/Perseus#4]
This project relies on code from a GPLv3 projects. That license should also apply to this project. it's a copyleft license and you can't relicense.

https://github.com/LGLTeam/Android-Hooking-Patching-Template
https://github.com/n0k0m3/Azur-Lane-Scripts-Autopatcher

You can be sent a cease and desist from the Free Soatware Foundation if you don't comply with GPLv3.

**Comment by Egoistically** [comment]
You are absolutely right, I'll make sure to pay more attention to licenses in the future.

One thing I'm curious about: is it enough if I only include parts which I have modified or added?
Just to keep things more tidy and avoid a cluttered repo.

Btw, quite the timing with today's banwave.

**Comment by zunda-arrow** [comment]
You have to include everything. GPLv3 applies to everything in the repo, even new files.

**Comment by zunda-arrow** [comment]
You can put the code in a different place as long as it's accessible as well.

**Comment by Egoistically** [comment]
I have removed all code under GPLv3 license, all that's left is (at most) under MIT.
If I understand correctly, under MIT I have no obligation to share the source code, thus this issue can be closed.

**Comment by Egoistically** [comment]
Due to some personal circumstances I couldn't release the source until now. I am sorry if I acted like an asshole.
https://github.com/Egoistically/Perseus/tree/src
