### ISSUE TITLE
need x86 .so for Android simulator

### ISSUE THREAD

**Issue by Trastice** [Egoistically/Perseus#5]
rt

**Comment by Egoistically** [comment]
Azur Lane does not ship x86 libs though, does it?

**Comment by HinBormah** [comment]
CN client actually have x86 libs,
and some emulators will prefer to use x86
so game's gonna stuck because it can't find libPerseus.so

**Comment by Egoistically** [comment]
Alright, I'll see what I can do

**Comment by Egoistically** [comment]
Added. Haven't tested it at all, let me know if it doesn't work.

**Comment by HinBormah** [comment]
Works perfectly to me, Thanks.
